# -*- coding: utf-8 -*-
"""Hugging_Face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANfj-S1tep377r3kX-ner0YjyYdhBWCR
"""

# STEP 1: Install Required Libraries
!pip uninstall -y transformers -q
!pip install -q transformers==4.40.2 torch

# STEP 2: Import Libraries
import transformers
from transformers import pipeline

print("Transformers version:", transformers.__version__)

# STEP 3: Load Summarization Model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# STEP 4: Define Function
def summarize_text(text, max_length=None, min_length=None):

    # Clean text
    text = " ".join(text.split())

    # Dynamic length handling
    if max_length is None:
        max_length = min(len(text) // 3, 150)

    if min_length is None:
        min_length = max(30, max_length // 3)

    # 1. Default summary
    summary_1 = summarizer(
        text,
        max_length=max_length,
        min_length=min_length,
        do_sample=False
    )

    # 2. Creative summary
    summary_2 = summarizer(
        text,
        max_length=max_length,
        min_length=min_length,
        do_sample=True,
        temperature=0.9
    )

    # 3. Conservative summary
    summary_3 = summarizer(
        text,
        max_length=max_length,
        min_length=min_length,
        do_sample=False,
        num_beams=5
    )

    # 4. Diverse summary
    summary_4 = summarizer(
        text,
        max_length=max_length,
        min_length=min_length,
        do_sample=True,
        top_k=50,
        top_p=0.95
    )

    # Output
    print("\n📝 Original Text:\n")
    print(text)

    print("\n📌 Summaries:\n")
    print("1️⃣ Default:\n", summary_1[0]['summary_text'])
    print("\n2️⃣ Creative:\n", summary_2[0]['summary_text'])
    print("\n3️⃣ Conservative:\n", summary_3[0]['summary_text'])
    print("\n4️⃣ Diverse:\n", summary_4[0]['summary_text'])

    return summary_1[0]['summary_text']

# STEP 5: Example Input
long_text = """
Artificial Intelligence (AI) is a rapidly evolving field of computer science focused on
creating intelligent machines capable of mimicking human cognitive functions such as
learning, problem-solving, and decision-making.

In recent years, AI has significantly impacted various industries, including healthcare,
finance, education, and entertainment. AI-powered applications, such as chatbots,
self-driving cars, and recommendation systems, have transformed the way we
interact with technology.

Machine learning and deep learning, subsets of AI, enable systems to learn from data
and improve over time without explicit programming.

However, AI also poses ethical challenges, such as bias in decision-making and
concerns over job displacement. As AI technology continues to advance,
it is crucial to balance innovation with ethical considerations.
"""
# STEP 6: Run
summarize_text(long_text)

