# -*- coding: utf-8 -*-
"""Semantic_Prompt_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMvxMoyF7SejdmlatAUdRwO_DM7cs1WE
"""

!pip install gensim
# Install Hugging Face Transformers for NLP pipelines
!pip install transformers
# Install NLTK for text preprocessing and tokenization
!pip install nltk
# Import libraries
import gensim.downloader as api
from transformers import pipeline
import nltk
import string
from nltk.tokenize import word_tokenize
# Download the 'punkt_tab' resource
nltk.download('punkt_tab')

# Load pre-trained word vectors
print("Loading pre-trained word vectors...")
word_vectors = api.load("glove-wiki-gigaword-100") # Load Word2Vec model
# Function to replace a keyword with a similar word using word embeddings
def replace_keyword_in_prompt(prompt, keyword, word_vectors, topn=1):
    words = word_tokenize(prompt)
    enriched_words = []
    for word in words:
        cleaned_word = word.lower().strip(string.punctuation)
        if cleaned_word == keyword.lower():
            try:
                similar_words = word_vectors.most_similar(cleaned_word, topn=topn)
                if similar_words:
                    replacement_word = similar_words[0][0]
                    print(f"Replacing '{word}' → '{replacement_word}'")
                    enriched_words.append(replacement_word)
                    continue
            except KeyError:
                print(f"'{keyword}' not found in the vocabulary. Using original word.")
        enriched_words.append(word)
    enriched_prompt = " ".join(enriched_words)
    print(f"\n🔹 Enriched Prompt: {enriched_prompt}")
    return enriched_prompt

# Load GPT-2 model
print("\n🔄 Loading GPT-2 model...")
generator = pipeline("text-generation", model="gpt2")
# Function to generate response
def generate_response(prompt, max_length=100):
    try:
        response = generator(prompt, max_length=max_length, num_return_sequences=1)
        return response[0]['generated_text']
    except Exception as e:
        print(f"Error generating response: {e}")
        return None

# Example usage
original_prompt = "Who is king?"
print(f"\n🔹 Original Prompt: {original_prompt}")
enriched_prompt = "Who is monarch?"

# Generate responses
print("\n🧠 Generating response for original prompt...")
original_response = generate_response(original_prompt)
print("\nOriginal Prompt Response:\n", original_response)
print("\n🧠 Generating response for enriched prompt...")
enriched_response = generate_response(enriched_prompt)
print("\nEnriched Prompt Response:\n", enriched_response)

# Comparison
if original_response and enriched_response:
    print("\n📊 Comparison:")
    print("Original Response Length:", len(original_response))
    print("Enriched Response Length:", len(enriched_response))
    print("Original Detail Level (periods):", original_response.count('.'))
    print("Enriched Detail Level (periods):", enriched_response.count('.'))

